config/routes.rb
Paoduro::Application.routes.draw do

  resources :compras

  resources :produtos

  devise_for :users do
        get "/users/sign_in", :to => "devise/sessions#new"
        get "/user/sign_out", :to => "devise/sessions#destroy"
  end

  resources :potzes

    root :to => 'welcome#index'

end

app/controllers/potzes_controller.rb
class PotzesController < ApplicationController


  def totalPotz
    
    totalAcumulado = 0
         
    Potze.where("user_id = ?", current_user.id).each do |item|
        
        totalAcumulado = totalAcumulado + item.cupom[0..2].to_i    
    
    end
    
    totalAcumulado
    
  end
  
  # GET /potzes
  # GET /potzes.json
  def index
    @potzes = Potze.where("user_id = ?", current_user.id);

    @totalAcumulado = totalPotz
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @potzes }
    end
  end

  # GET /potzes/1
  # GET /potzes/1.json
  def show
    
    @potze = Potze.find(params[:id])
    
    @totalAcumulado = totalPotz
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @potze }
    end
  end

  # GET /potzes/new
  # GET /potzes/new.json
  def new
    @potze = Potze.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @potze }
    end
  end

  # GET /potzes/1/edit
  def edit
    @potze = Potze.find(params[:id])
  end

  # POST /potzes
  # POST /potzes.json
  def create
    @potze = Potze.new(params[:potze])
    @potze.user_id = current_user.id
    respond_to do |format|
      if @potze.save
        format.html { redirect_to @potze, :notice => 'Potze was successfully created.' }
        format.json { render :json => @potze, :status => :created, :location => @potze }
      else
        format.html { render :action => "new" }
        format.json { render :json => @potze.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /potzes/1
  # PUT /potzes/1.json
  def update
    @potze = Potze.find(params[:id])

    respond_to do |format|
      if @potze.update_attributes(params[:potze])
        format.html { redirect_to @potze, :notice => 'Potze was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @potze.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /potzes/1
  # DELETE /potzes/1.json
  def destroy
    @potze = Potze.find(params[:id])
    @potze.destroy

    respond_to do |format|
      format.html { redirect_to potzes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/potzes_helper.rb
module PotzesHelper
end

app/views/potzes/_form.html.erb
<%= form_for(@potze , :html => { :class => 'form-stacked' } ) do |f| %>
  <% if @potze.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@potze.errors.count, "error") %> prohibited this potze from being saved:</h2>

      <ul>
      <% @potze.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cupom %><br />
    <%= f.text_field :cupom %>
  </div>
  <div class="actions">
    <%= f.submit 'Trocar',:class => 'btn primary' %>
  </div>
<% end %>

app/views/potzes/_titulo.html.erb
<h1>Saldo de potz atual é: <%= @totalAcumulado%></h1>

app/views/potzes/edit.html.erb
<h1>Editing potze</h1>

<%= render 'form' %>

<%= link_to 'Show', @potze %> |
<%= link_to 'Back', potzes_path %>

app/views/potzes/index.html.erb
<table class="zebra-striped"  style="width:97%">
<thead>
  <tr>
    <th style="width:90%">Cupom</th>
    <th>Quantidade</th>
  </tr>
</thead>
<tbody>
<% @potzes.each do |potze| %>
  <tr>
    <td><%= potze.cupom %></td>
        <td><%= potze.cupom[0..2].to_s %></td>
  </tr>
<% end %>
</tbody>
</table>
<%= link_to 'Troque Potz', new_potze_path %>
<% content_for :titulo, render(:partial => 'titulo') %>

app/views/potzes/new.html.erb
<h1>Trocando Potz</h1>
<%= render 'form' %>

app/views/potzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cupom:</b>
  <%= @potze.cupom %>
  <b>Total Potz acumulado:</b>
  <%= @totalAcumulado %>
</p>

<p>
  <b>User:</b>
  <%= @potze.user.email %>
</p>


<%= link_to 'Edit', edit_potze_path(@potze) %> |
<%= link_to 'Back', potzes_path %>