config/routes.rb
Paoduro::Application.routes.draw do

  resources :compras

  resources :produtos

  devise_for :users do
        get "/users/sign_in", :to => "devise/sessions#new"
        get "/user/sign_out", :to => "devise/sessions#destroy"
  end

  resources :potzes

    root :to => 'welcome#index'

end

app/models/compra.rb
class Compra < ActiveRecord::Base
  belongs_to :produto
  belongs_to :user
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.where('cliente =?',  current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @compras }
    end
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
    @compra = Compra.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @compra }
    end
  end

  # GET /compras/new
  # GET /compras/new.json
  def new
    @compra = Compra.new

    @produtos = Produto.where("user_id !=?", current_user.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @compra }
    end
  end

  # GET /compras/1/edit
  def edit
    @compra = Compra.find(params[:id])
  end

  # POST /compras
  # POST /compras.json
  def create

    params[:produto_id].each do |p|

       @teste = Produto.find(p)

       @compra =  Compra.new
       @compra.produto_id = p
       @compra.user_id = Produto.find(p).user_id
       @compra.cliente = current_user.id
       @compra.save

    end

       redirect_to(compras_url)
  end

  # PUT /compras/1
  # PUT /compras/1.json
  def update
    @compra = Compra.find(params[:id])

    respond_to do |format|
      if @compra.update_attributes(params[:compra])
        format.html { redirect_to @compra, :notice => 'Compra was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @compra.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra = Compra.find(params[:id])
    @compra.destroy

    respond_to do |format|
      format.html { redirect_to compras_url }
      format.json { head :ok }
    end
  end
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/views/compras/_form.html.erb
<%= form_for(@compra, :html => {:class => 'form-stacked'}) do |f| %>
  <% if @compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% @compra.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="zebra-striped">
 <thead>
  <tr>
    <th>Foto</th>
    <th>Descricao</th>
    <th>Preco</th>
    <th c>Comprar</th>
  </tr>
</thead>
 <tbody>
<% @produtos.each do |produto| %>
  <tr>
    <td><%= image_tag produto.foto, :width => '64px' %></td>
    <td><p>Por: <%= produto.user.nome %></p><%= link_to produto.descricao, produto %></td>
    <td><%= produto.preco %></td>
    <td style="text-align:center"><%= check_box_tag "produto_id[]", produto.id %></td>
  </tr>
<% end %>
 </tbody>
</table>
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn primary'%> <%= link_to 'Voltar', compras_path, :class => 'btn' %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing compra</h1>

<%= render 'form' %>

<%= link_to 'Show', @compra %> |
<%= link_to 'Back', compras_path %>

app/views/compras/index.html.erb
<h1>Compras</h1>
<table class="zebra-striped">
<thead>
  <tr>
    <th>Produto</th>
    <th>De: </th>
    <th>Data compra</th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @compras.each do |compra| %>
  <tr>
    <td><%= image_tag compra.produto.foto, :width => '64px' %></td>
    <td><%= compra.user.nome %></td>
    <td><%= compra.created_at %></td>
    <td><%= link_to 'Destroy', compra, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</tbody>
</table>
<br />
<%= link_to 'Nova Compra', new_compra_path, :class => 'btn primary' %>

app/views/compras/new.html.erb
<h1>Nova compra</h1>

<%= render 'form' %>

app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Produto:</b>
  <%= @compra.produto %>
</p>

<p>
  <b>User:</b>
  <%= @compra.user.nome %>
</p>

<p>
  <b>Data compra:</b>
  <%= @compra.created_at %>
</p>

<p>
  <b>Status:</b>
  <%= @compra.status %>
</p>


<%= link_to 'Edit', edit_compra_path(@compra) %> |
<%= link_to 'Back', compras_path %>