config/routes.rb
Paoduro::Application.routes.draw do

  resources :compras

  resources :produtos

  devise_for :users do
        get "/users/sign_in", :to => "devise/sessions#new"
        get "/user/sign_out", :to => "devise/sessions#destroy"
  end

  resources :potzes

    root :to => 'welcome#index'

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  belongs_to :user

  def my_user

    user.id

  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.where('user_id =?', current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])
    @produto.user = current_user
    @produto.status = false

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, :notice => 'Produto was successfully created.' }
        format.json { render :json => @produto, :status => :created, :location => @produto }
      else
        format.html { render :action => "new" }
        format.json { render :json => @produto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to @produto, :notice => 'Produto was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @produto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto, :html => {:class => 'form-stacked'}) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :preco %><br />
    <%= f.text_field :preco %>
  </div>
  <div class="field">
    <%= f.label :foto %><br />
    <%= f.text_field :foto %>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn primary' %> <%= link_to 'Cancelar', produtos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<h1>Produtos</h1>
<table class="zebra-striped">
 <thead>
  <tr>
    <th>Foto</th>
    <th>Descricao</th>
    <th>Preco</th>
    <th>Vendido</th>
    <th>Ação</th>
  </tr>
</thead>
 <tbody>
<% @produtos.each do |produto| %>
  <tr>
    <td><%= image_tag produto.foto, :width => '64px' %></td>
    <td><%= link_to produto.descricao, produto %></td>
    <td><%= produto.preco %></td>
    <td><%= produto.status %></td>
    <td><%= link_to 'Deletar', produto, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
 </tbody>
</table>
<br /><%= link_to 'Novo Produto', new_produto_path, :class => 'btn primary' %>

app/views/produtos/new.html.erb
<h1>Novo produto</h1>

<%= render 'form' %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= image_tag @produto.foto %>
</p>

<p>
  <b>Preco:</b>
  <%= @produto.preco %>
</p>

<p>
  <b>Descricao:</b>
  <%= @produto.descricao %>
</p>

<p>
  <b>User:</b>
  <%= @produto.user %>
</p>

<p>
  <b>Status:</b>
  <%= @produto.status %>
</p>


<%= link_to 'Voltar', new_compra_path unless current_user.id == @produto.user_id %>
<%= link_to 'Edit', edit_produto_path(@produto) if current_user.id == @produto.user_id %> |
<%= link_to 'Back', produtos_path %>